/**
 * \file
 *
 * \brief Board arduino interface definitions
 */

/**
 * \file
 *
 * The Clear BSD License
 * Copyright Semtech Corporation 2022. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted (subject to the limitations in the disclaimer
 * below) provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Semtech corporation nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY
 * THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 * CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL SEMTECH CORPORATION BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef SMTC_ARDUINO_COMPAT_H_
#define SMTC_ARDUINO_COMPAT_H_

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC CONSTANTS --------------------------------------------------------
 */

#define SMTC_ARDUINO_PORT_A0 GPIOA
#define SMTC_ARDUINO_PORT_A1 GPIOA
#define SMTC_ARDUINO_PORT_A2 GPIOA
#define SMTC_ARDUINO_PORT_A3 GPIOB
#define SMTC_ARDUINO_PORT_A4 GPIOC
#define SMTC_ARDUINO_PORT_A5 GPIOC
#define SMTC_ARDUINO_PORT_D0 GPIOA
#define SMTC_ARDUINO_PORT_D1 GPIOA
#define SMTC_ARDUINO_PORT_D2 GPIOA
#define SMTC_ARDUINO_PORT_D3 GPIOB
#define SMTC_ARDUINO_PORT_D4 GPIOB
#define SMTC_ARDUINO_PORT_D5 GPIOB
#define SMTC_ARDUINO_PORT_D6 GPIOB
#define SMTC_ARDUINO_PORT_D7 GPIOA
#define SMTC_ARDUINO_PORT_D8 GPIOA
#define SMTC_ARDUINO_PORT_D9 GPIOC
#define SMTC_ARDUINO_PORT_D10 GPIOB
#define SMTC_ARDUINO_PORT_D11 GPIOA
#define SMTC_ARDUINO_PORT_D12 GPIOA
#define SMTC_ARDUINO_PORT_D13 GPIOA
#define SMTC_ARDUINO_PORT_D14 GPIOB
#define SMTC_ARDUINO_PORT_D15 GPIOB

#define SMTC_ARDUINO_PIN_A0 ( 0 )
#define SMTC_ARDUINO_PIN_A1 ( 1 )
#define SMTC_ARDUINO_PIN_A2 ( 4 )
#define SMTC_ARDUINO_PIN_A3 ( 0 )
#define SMTC_ARDUINO_PIN_A4 ( 1 )
#define SMTC_ARDUINO_PIN_A5 ( 0 )
#define SMTC_ARDUINO_PIN_D0 ( 3 )
#define SMTC_ARDUINO_PIN_D1 ( 2 )
#define SMTC_ARDUINO_PIN_D2 ( 10 )
#define SMTC_ARDUINO_PIN_D3 ( 3 )
#define SMTC_ARDUINO_PIN_D4 ( 5 )
#define SMTC_ARDUINO_PIN_D5 ( 4 )
#define SMTC_ARDUINO_PIN_D6 ( 10 )
#define SMTC_ARDUINO_PIN_D7 ( 8 )
#define SMTC_ARDUINO_PIN_D8 ( 9 )
#define SMTC_ARDUINO_PIN_D9 ( 7 )
#define SMTC_ARDUINO_PIN_D10 ( 6 )
#define SMTC_ARDUINO_PIN_D11 ( 7 )
#define SMTC_ARDUINO_PIN_D12 ( 6 )
#define SMTC_ARDUINO_PIN_D13 ( 5 )
#define SMTC_ARDUINO_PIN_D14 ( 9 )
#define SMTC_ARDUINO_PIN_D15 ( 8 )

#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_A0 ( LL_SYSCFG_EXTI_LINE0 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_A1 ( LL_SYSCFG_EXTI_LINE1 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_A2 ( LL_SYSCFG_EXTI_LINE4 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_A3 ( LL_SYSCFG_EXTI_LINE0 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_A4 ( LL_SYSCFG_EXTI_LINE1 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_A5 ( LL_SYSCFG_EXTI_LINE0 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D0 ( LL_SYSCFG_EXTI_LINE3 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D1 ( LL_SYSCFG_EXTI_LINE2 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D2 ( LL_SYSCFG_EXTI_LINE10 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D3 ( LL_SYSCFG_EXTI_LINE3 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D4 ( LL_SYSCFG_EXTI_LINE5 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D5 ( LL_SYSCFG_EXTI_LINE4 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D6 ( LL_SYSCFG_EXTI_LINE10 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D7 ( LL_SYSCFG_EXTI_LINE8 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D8 ( LL_SYSCFG_EXTI_LINE9 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D9 ( LL_SYSCFG_EXTI_LINE7 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D10 ( LL_SYSCFG_EXTI_LINE6 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D11 ( LL_SYSCFG_EXTI_LINE7 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D12 ( LL_SYSCFG_EXTI_LINE6 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D13 ( LL_SYSCFG_EXTI_LINE5 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D14 ( LL_SYSCFG_EXTI_LINE9 )
#define SMTC_ARDUINO_LL_SYSCFG_EXTI_LINE_D15 ( LL_SYSCFG_EXTI_LINE8 )

#define SMTC_ARDUINO_EXTI_IRQn_A0 ( EXTI0_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_A1 ( EXTI1_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_A2 ( EXTI4_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_A3 ( EXTI0_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_A4 ( EXTI1_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_A5 ( EXTI0_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D0 ( EXTI3_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D1 ( EXTI2_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D2 ( EXTI15_10_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D3 ( EXTI3_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D4 ( EXTI9_5_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D5 ( EXTI4_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D6 ( EXTI15_10_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D7 ( EXTI9_5_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D8 ( EXTI9_5_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D9 ( EXTI9_5_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D10 ( EXTI9_5_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D11 ( EXTI9_5_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D12 ( EXTI9_5_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D13 ( EXTI9_5_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D14 ( EXTI9_5_IRQn )
#define SMTC_ARDUINO_EXTI_IRQn_D15 ( EXTI9_5_IRQn )

#endif  // SMTC_ARDUINO_COMPAT_H_

/* --- EOF ------------------------------------------------------------------ */
